In [ ]:
EXERCISE 1 — Array Creation (Foundations)
Objective: Prove you can create arrays deliberately, not by habit.
# TASKS:
# 1. Create an array with values [0, 1, 2, ..., 20]
# 2. Create an array with 50 evenly spaced values between 0 and 10
# 3. Create an array with 100 random values (normal distribution)
# 4. Create an array with 10 zeros


# Constraints:
# - No loops
# - Use NumPy constructors only

In [23]:
#1
import numpy as np
a = np.arange(0, 21, 1)
print(a)

#2
import numpy as np
b = np.linspace(0, 10, 50)
print(b)

#3
c = np.random.randn(100)
print(c)

#4
d = np.zeros(10)
print(d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]
[ 1.18684758e+00  9.82113932e-01  1.16649778e-02  7.42453104e-01
  1.54736955e+00 -8.20263755e-01 -7.39533460e-01 -9.75538727e-01
  8.40125714e-01  9.34442537e-01  1.30989193e+00  9.55996256e-01
  2.04862038e+00  5.68940835e-02  7.65016756e-01  2.39906907e-02
  6.80431666e-01 -4.24271566e-01  7.74260945e-02  8.86588958e-01


In [ ]:
EXERCISE 2 — Indexing & Slicing (Precision)
Objective: Access data surgically, without guessing.
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
# TASKS:
# 1. Access the 3rd element
# 2. Access the last 3 elements
# 3. Access elements at even indices (0, 2, 4, ...)
# 4. Reverse the array
# 5. Access elements from the 3rd to the second‑to‑last, stepping by 2


# Constraints:
# - Indexing / slicing only
# - No helper variables unless strictly necessary

In [69]:
import numpy as np
arr = np.array([5, 10, 15, 20, 25, 30, 35, 40, 45, 50])
#1
print(arr[2])

#2
last_3 = arr[-3:]
print(last_3)

#3
even_i = arr[::2]
print(even_i)

#4
reverse = arr[::-1]
print(reverse)

#5
fun = arr[2:-1:2]
print(fun)

15
[40 45 50]
[ 5 15 25 35 45]
[50 45 40 35 30 25 20 15 10  5]
[15 25 35 45]


In [ ]:
EXERCISE 3 — Vectorized Operations (No Loops, Ever)
Objective: Eliminate loop‑thinking completely.
data = np.array([1,2,3,4,5,6,7,8,9,10])
# TASKS:
# 1. Multiply all elements by 3
# 2. Square all elements
# 3. Compute the square root of each element
# 4. Add 100 to each element


# Constraints:
# - One NumPy expression per task
# - No intermediate Python lists

In [91]:
import numpy as np
data = np.array([1,2,3,4,5,6,7,8,9,10])

#1
mult = data*3
print(mult)

#2
squa = data**2
print(squa)

#3
root = np.sqrt(data)
print(root)

#4
add = data+100
print(add)

[ 3  6  9 12 15 18 21 24 27 30]
[  1   4   9  16  25  36  49  64  81 100]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
[101 102 103 104 105 106 107 108 109 110]


In [ ]:
EXERCISE 4 — Applied Data Analysis (Biomedical Context)
Objective: Use NumPy like a scientist, not a student.
Simulate body temperature measurements (°C)
1 measurement per hour, 24 hours
Mean = 37.0°C, Std = 0.3°C
# TASKS:
# 1. Create the temperature array using NumPy
# 2. Compute:
# - Maximum temperature
# - Minimum temperature
# - Mean temperature
# - Number of measurements > 37.5°C (fever threshold)


# Constraints:
# - Use NumPy statistical functions
# - Fever count MUST use boolean masking

In [131]:
#1
import numpy as np
temp = np.random.normal(loc=37.0, scale=0.3, size=24)
#2
print(f"Max: {np.max(temp)}")
print(f"Min: {np.min(temp)}")
print(f"Mean: {np.mean(temp)}")
fever_count = np.sum(temp>37.5) #temp>37.5, gives an array of True´s / False´s
print(f"Fever Count: {fever_count}")

Max: 38.00270971643486
Min: 36.314043628592664
Mean: 36.99960248689434
Fever Count: 2


In [ ]:
EXERCISE 5 — Signal Generation (ECG Preparation)
Objective: Think in discrete time and signals.
# TASKS:
# 1. Create a time vector from 0 to 2 seconds with fs = 100 Hz
# (use np.arange, step = 1/fs)
# 2. Create a sinusoidal signal:
# y = sin(2π × 5 × t)
# Frequency = 5 Hz
# 3. Print:
# - Number of samples
# - Signal maximum
# - Signal minimum
# - Shape of t and y

# Constraints:
# - t and y must have identical shapes
# - No hard‑coded sample counts

In [175]:
#1
import numpy as np
fs=100
f=5
step = 1/fs
vector= np.arange(0,2, step)

#2
y = np.sin(2 * np.pi * f * vector) #sin(2π × f × t)

#3
print(f"Number: {len(vector)}")
print(f"Max: {np.max(y):.2f}") #:.2f duas casas decimais em float
print(f"Min: {np.min(y):.2f}") 
print(f"Shape t: {vector.shape}")
print(f"Shape y: {y.shape}")

Number: 200
Max: 1.00
Min: -1.00
Shape t: (200,)
Shape y: (200,)
